spring.application.name=core

spring.datasource.url=jdbc:postgresql://db/pmocdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false