spring.application.name=core

spring.datasource.url=jdbc:postgresql://localhost:5432/dbcore
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

spring.standard.email=emailDoCore123@gmail.com
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=aqui_e_secreto_tenho_q_atualizar
spring.mail.password=aqui_e_secreto_tenho_q_atualizar
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false